CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    passwd BYTEA NOT NULL,
    created BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS codes (
    id SERIAL PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    owner INTEGER REFERENCES users (id) NOT NULL,
    created BIGINT NOT NULL,
    expired BIGINT NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_code ON codes (code);

CREATE TABLE IF NOT EXISTS referrals (
    id INTEGER REFERENCES users (id) NOT NULL,
    referrer_id INTEGER REFERENCES users (id) NOT NULL,
    code_id INTEGER REFERENCES codes (id) NOT NULL
);