# Environment
env: "local" # local, dev, prod
# PostgreSQL
storage_path: "localhost:5432"
storage_db: "referrals"
storage_user: "admin"
storage_passwd: "POSTGRES_PASSWD"
# JWT Auth
jwt_secret: "JWT_SECRET"
token_ttl: 15m
# Referral Codes
code_ttl: 24h
# HTTP Server
http_server:
  address: "0.0.0.0:8080"
  read_timeout: 15s
  write_timeout: 30s
  idle_timeout: 60s